### ISSUE TITLE
Model Binding

### ISSUE THREAD

**Issue by grodriguez85** [scoutforpets/ember-fullcalendar#31]
The basic example shows how to create the array of events, but what if I want to bind the calendar with an event model?

On my route, I return as my model this.get('store').peekAll('event'); and when calling the full-calendar helper I set events=model but nothing happens. Maybe because my model isn't as an array of events. 

The event model has the title, start and end attributes and I'm using ember 2.7. Thanks in advance!

**Comment by getaclue** [comment]
Hey guys!

@grodriguez85 good point. I ran into this myself recently.

Just noticed that as well.
Ended up finding help via http://ember387.rssing.com/chan-57747182/all_p7.html and doing the `forEach` after grabbing all of the events via `findAll`. Just like you, my model was structures around what fullCalendar expects.

If this isn't built in, are there any hints for looking at making this happen?

Thanks,
Alex

**Comment by jamesdixon** [comment]
Hi guys, sorry for the delayed reply.

Check out the `eventDataTransform` callback that FC provides: https://fullcalendar.io/docs/event_data/eventDataTransform/

You can easily hook into it to transform your Ember models into what FC expects.

Closing this -- feel free to re-open.

James

**Comment by joshuairl** [comment]
@getaclue @grodriguez85 @jamesdixon Has anyone successfully done this? Where or possibly built a layer of abstraction so as to make ember-fullcalendar a bit more "ember" and a lot less.... well whatever it is now...

Just seems like there should be a built in "eventSource" that speaks JSON API Spec or Ember Data in a sense right from the start.  I'm okay with contributing this type of feature myself, I just wasn't sure of the best implementation since my knowledge of both fullcalendar and ember are... well... unequal.

Anyone care to share some code or examples of their implementation of getting a findAll and two-way data binding between changes in the fullcalendar views and the data pulling / syncing with ember-data? Even if its just a huge-ass controller doing it all.

**Comment by joshuairl** [comment]
Oh and I forgot to say Thank you for building such a great addition to Ember.  I appreciate your work so far!  Great stuff.
